SportsPromo.App.WebSiteAdm/Controllers/ChecagemController.cs
using SportsPromo.App.Interfaces.Manipuladores;
using SportsPromo.App.Modelos;
using SportsPromo.Comum.Dados;
using SportsPromo.Comum.Exceptions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace SportsPromo.App.WebSiteAdm.Controllers
{
    public class ChecagemController : Controller
    {
        public ActionResult Index()
        {
            return View("OnePage");
        }
    }
}

SportsPromo.App.WebSiteAdm/Views/Checagem/OnePage.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Checagem")
</p>
@*<script>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

    </script>*@

<table class="table" id="tabela-checagem">
    <thead>
        <tr>
            <th data-key="Id" data-sort="true">
                Id
            </th>
            <th data-key="Rfid" data-sort="true">
                Rfid
            </th>
            <th>
                Personalizada
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<nav aria-label="Page navigation" id="tabela-checagem-paginador"></nav>

<!-- Modal -->
<div class="modal fade" id="modal-checagem" tabindex="-1" role="dialog" aria-labelledby="modal-checagem-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-checagem-label">Modal title</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="checagemId" value="0" />
                <div class="form-group">
                    <label for="checagemRfid">Rfid</label>
                    <input type="text" class="form-control" id="checagemRfid" placeholder="Rfid">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="salvarChecagem">Salvar</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    
    
    @Scripts.Render("~/Scripts/GridJs.js")

    <script>
        var ComboItens = [];
        InstalarCombo();
        function GetSelecionados() {
            var resultado = [];
            var combo = $("#meu-combo a.selecionado");
            combo.each(function () {
                resultado.push($(this).data("valor"));
            });
            return resultado;
        }
        function SelecioneComboItem(item) {
            $(item).toggleClass("selecionado");

            var dataItem = $(item).data("valor");

            var texto = GetSelecionados().map(item => item.texto).sort().join(", ");
            $(item).parents(".combo-simples").find(".combo-texto").html(texto);

            dataItem.elemento.removeAttr("selected")

            if ($(item).hasClass("selecionado")) {
                dataItem.elemento.attr("selected", "selected")
            }

        }

        function ExtrairDados() {
            $("#selectera option").each(function () {

                ComboItens.push({ valor: $(this).val(), texto: $(this).html(), elemento: $(this) });
            });
            return ComboItens;
        }

        function InstalarCombo() {
            var combo = $("#meu-combo");
            var dados = ExtrairDados();
            var lista = $("<ul/>");
            dados.forEach(function (item) {
                var itemLista = $("<li />");
                var botaoLista = $("<a href=\"javascript:;\">" + item.texto + "</a>");
                botaoLista.on("click", function () {
                    SelecioneComboItem(this);
                });
                botaoLista.data("valor", item);
                itemLista.append(botaoLista);
                lista.append(itemLista);
            });

            combo.append(lista);

            $(".combo-botao").on("click", function () {
                combo.toggleClass("aberto");
            });
        }



        var esporteGrid;
        $(document).ready(function () {
            var gridOptions = {
                Url: "http://localhost:44331/api/ChecagemApi/index/",
                Colunas: [
                    {
                        NomeDoCampo: "Id",
                        AtributosHtml: "",
                        CallbackDeRenderizacao: function (itemLinha, atributoColuna) {
                            var texto = itemLinha[atributoColuna];
                            var celula = $("<td />").addClass("text-right").append(texto);
                            return celula;
                        }
                    },
                    "Rfid",
                    {
                        CallbackDeRenderizacao: function (itemLinha, atributoColuna) {

                            var texto = `${itemLinha.Id} - ${itemLinha.Nome}`;

                            var linkEdicao = $("<a/>")
                                .attr("href", "javascript:;")
                                .addClass("btn btn-primary")
                                .append("Editar")
                                .on("click", function () {
                                    ExibeFormularioEdicao(itemLinha.Id);
                                });
                            var celula = $("<td />").addClass("text-right").append(linkEdicao);

                            return celula;
                        }
                    }
                ],
                ConteinerDoPaginador: "#tabela-checagem-paginador"
            };
            checagemGrid = SetupGrid("#tabela-checagem", gridOptions);
            $("#salvarChecagem").on("click", function () { SalvarChecagem() });

        });
        function ExibeFormularioEdicao(itemId) {
            $.ajax("http://localhost:44331/api/ChecagemApi/get/", {
                method: "GET",
                data: { id: itemId }
            }).done(function (response, textStatus, jqXHR) {
                var modalChecagem = $("#modal-checagem");
                $("#checagemId").val(response.Id);
                $("#checagemRfid").val(response.Rfid);
                modalChecagem.modal('show');
            });
        };

        function SalvarChecagem() {

            var putUrl = "http://localhost:44331/api/ChecagemApi/put/?id=";

            var checagemItem = {
                Id: $("#checagemId").val(),
                Rfid: $("#checagemRfid").val(),
            }

            $.ajax(putUrl + checagemItem.Id, {
                method: "PUT",
                data: checagemItem
            }).done(function (response, textStatus, jqXHR) {
                checagemGrid.Recarregar();
                var modalChecagem = $("#modal-checagem");
                modalChecagem.modal('hide');
            });
        }
    </script>
}