SportsPromo.App.WebSiteAdm/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SportsPromo.App.Core.Modelos;
using SportsPromo.App.Interfaces.Manipuladores;
using SportsPromo.App.WebSiteAdm.Models;
using SportsPromo.Comum.Dados;
using SportsPromo.Comum.Exceptions;
using SportsPromo.Comum.Helpers;

namespace SportsPromo.App.WebSiteAdm.Controllers
{
    public class CategoriaController : Controller
    {
        protected readonly ICategoriaManipulador CategoriaManipulador;
        public CategoriaController(ICategoriaManipulador categoriaManipulador)
        {
            CategoriaManipulador = categoriaManipulador;
        }
        public ActionResult OnePage()
        {
            return View();
        }


        // GET: CategoriaApps
        public ActionResult Index(int? page, string sort, int? direction)
        {

            var consulta = new PaginadoOrdenado<CategoriaApp>()
            {
                PaginaAtual = page ?? 1,
                ItensPorPagina = 6,
                OrdemNome = sort ?? "Id",
                OrdemDirecao = direction ?? 0
            };

            var result = CategoriaManipulador.Listar(consulta);

            return View(result);
        }

        // GET: CategoriaApps/Details/5
        public ActionResult Details(long? id)
        {



            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var CategoriaApp = CategoriaManipulador.Pegar(id.Value);

            if (CategoriaApp == null)
            {
                return HttpNotFound();
            }
            return View(CategoriaApp);
        }

        // GET: CategoriaApps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriaApps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome")] CategoriaApp CategoriaApp)
        {
            if (ModelState.IsValid)
            {
                var result = CategoriaManipulador.Adicionar(CategoriaApp);
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(CategoriaApp);
        }

        // GET: CategoriaApps/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var CategoriaApp = CategoriaManipulador.Pegar(id.Value);

            if (CategoriaApp == null)
            {
                return HttpNotFound();
            }
            return View(CategoriaApp);
        }

        // POST: CategoriaApps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome")] CategoriaApp CategoriaApp)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var result = CategoriaManipulador.Alterar(CategoriaApp);
                    if (result)
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (AppException ex)
                {

                    ex.ValidationResults.ToList().ForEach(e =>
                    {
                        var localName = string.Empty;

                        if (e.MemberNames.Any())
                        {
                            var memberName = e.MemberNames.First();
                            switch (memberName)
                            {
                                case "CategoriaNome":
                                    localName = "Nome";
                                    break;
                                default:
                                    break;
                            }
                        }
                        if (string.IsNullOrEmpty(localName))
                        {
                            ModelState.AddModelError(string.Empty, e.ErrorMessage);
                        }
                        else
                        {
                            ModelState.AddModelError(localName, e.ErrorMessage);
                        }
                    });
                    ModelState.AddModelError(string.Empty, "Problemas ao Alterar!");

                }
            }
            return View(CategoriaApp);
        }

        // GET: CategoriaApps/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var CategoriaApp = CategoriaManipulador.Pegar(id.Value);

            if (CategoriaApp == null)
            {
                return HttpNotFound();
            }
            return View(CategoriaApp);
        }

        // POST: CategoriaApps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var result = CategoriaManipulador.Deletar(id);

            return RedirectToAction("Index");
        }
    }
}

SportsPromo.App.WebSiteAdm/Views/Categoria/OnePage.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>OnePage</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Categoria")
</p>
@*<script>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

    </script>*@

<table class="table" id="tabela-categoria">
    <thead>
        <tr>
            <th data-key="Id" data-sort="true">
                Id
            </th>
            <th data-key="Nome" data-sort="true">
                Nome
            </th>
            <th>
                Personalizada
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
<nav aria-label="Page navigation" id="tabela-categoria-paginador"></nav>

<!-- Modal -->
<div class="modal fade" id="modal-categoria" tabindex="-1" role="dialog" aria-labelledby="modal-categoria-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-categoria-label">Alteração do nome da Categoria</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="categoiraId" value="0" />
                <div class="form-group">
                    <label for="categoriaNome">Categoria</label>
                    <input type="text" class="form-control" id="categoriaNome" placeholder="Nome da categoria">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="salvarCategoria">Salvar</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/Scripts/jquery.grid-sport.js")

    <script>

        var categoriaGrid;

        $(document).ready(function () {
            var gridOptions = {
                Url: "http://localhost:44331/api/categoriaapi/index/",
                Colunas: [
                    {
                        NomeDoCampo: "Id",
                        AtributosHtml: "",
                        CallbackDeRenderizacao: function (itemLinha, atributoColuna) {
                            var texto = itemLinha[atributoColuna];
                            var celula = $("<td />").addClass("text-right").append(texto);
                            return celula;
                        }
                    },
                    "Nome",
                    {
                        CallbackDeRenderizacao: function (itemLinha, atributoColuna) {

                            var texto = `${itemLinha.Id} - ${itemLinha.Nome}`;

                            var linkEdicao = $("<a/>")
                                .attr("href", "javascript:;")
                                .addClass("btn btn-primary")
                                .append("Editar")
                                .on("click", function () {
                                    ExibeFormularioEdicao(itemLinha.Id);
                                });
                            var celula = $("<td />").addClass("text-right").append(linkEdicao);

                            return celula;
                        }
                    }
                ],
                ConteinerDoPaginador: "#tabela-categoria-paginador"
            };
            categoriaGrid = $("#tabela-categoria").GridSport(gridOptions);

            //categoriaGrid = SetupGrid("#tabela-categoria", gridOptions);
            $("#salvarcategoria").on("click", function () { SalvarCategoria() });
        });
        function ExibeFormularioEdicao(itemId) {
            $.ajax("http://localhost:44331/api/categoriaapi/get/", {
                method: "GET",
                data: { id: itemId }
            }).done(function (response, textStatus, jqXHR) {
                var modalCategoria = $("#modal-categoria");
                $("#categoriaId").val(response.Id);
                $("#categoriaNome").val(response.Nome);
                modalCategoria.modal('show');
            });
        };

        function SalvarCategoria() {

            var putUrl = "http://localhost:44331/api/categoriaapi/put/?id=";

            var categoriaItem = {
                Id: $("#categoriaId").val(),
                Nome: $("#categoriaNome").val(),
            }

            $.ajax(putUrl + categoriaItem.Id, {
                method: "PUT",
                data: categoriaItem
            }).done(function (response, textStatus, jqXHR) {
                categoriaGrid.Recarregar();
                var modalcategoria = $("#modal-categoria");
                modalCategoria.modal('hide');
            });
        }


    </script>

}