SportsPromo.App.WebSiteAdm/Controllers/EsporteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SportsPromo.App.Core.Modelos;
using SportsPromo.App.Interfaces.Manipuladores;
using SportsPromo.App.WebSiteAdm.Models;
using SportsPromo.Comum.Dados;
using SportsPromo.Comum.Exceptions;
using SportsPromo.Comum.Helpers;

namespace SportsPromo.App.WebSiteAdm.Controllers
{
    public class EsporteController : Controller
    {

        protected readonly IEsporteManipulador EsporteManipulador;
        public EsporteController(IEsporteManipulador esporteManipulador)
        {
            EsporteManipulador = esporteManipulador;
        }
        public ActionResult OnePage()
        {
            return View();
        }


        // GET: EsporteApps
        public ActionResult Index(int? page, string sort, int? direction)
        {

            var consulta = new PaginadoOrdenado<EsporteApp>()
            {
                PaginaAtual = page ?? 1,
                ItensPorPagina = 6,
                OrdemNome = sort ?? "Id",
                OrdemDirecao = direction ?? 0
            };

           var result = EsporteManipulador.Listar(consulta);

            return View(result);
        }

        // GET: EsporteApps/Details/5
        public ActionResult Details(long? id)
        {



            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var EsporteApp = EsporteManipulador.Pegar(id.Value);

            if (EsporteApp == null)
            {
                return HttpNotFound();
            }
            return View(EsporteApp);
        }

        // GET: EsporteApps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EsporteApps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome")] EsporteApp EsporteApp)
        {
            if (ModelState.IsValid)
            {
                var result = EsporteManipulador.Adicionar(EsporteApp);
                if (result > 0)
                {
                    return RedirectToAction("Index");
                }
            }

            return View(EsporteApp);
        }

        // GET: EsporteApps/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var EsporteApp = EsporteManipulador.Pegar(id.Value);

            if (EsporteApp == null)
            {
                return HttpNotFound();
            }
            return View(EsporteApp);
        }

        // POST: EsporteApps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPut]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome")] EsporteApp esporteApp)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var result = EsporteManipulador.Alterar(esporteApp);
                    if (result)
                    {
                        return RedirectToAction("Index");
                    }
                }
                catch (AppException ex)
                {

                    ex.ValidationResults.ToList().ForEach(e =>
                    {
                        var localName = string.Empty;

                        if (e.MemberNames.Any())
                        {
                            var memberName = e.MemberNames.First();
                            switch (memberName)
                            {
                                case "EsporteNome":
                                    localName = "Nome";
                                    break;
                                default:
                                    break;
                            }
                        }
                        if (string.IsNullOrEmpty(localName))
                        {
                            ModelState.AddModelError(string.Empty, e.ErrorMessage);
                        }
                        else
                        {
                            ModelState.AddModelError(localName, e.ErrorMessage);
                        }
                    });
                    ModelState.AddModelError(string.Empty, "Problemas ao Alterar!");

                }
            }
            return View(esporteApp);
        }

        // GET: EsporteApps/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var EsporteApp = EsporteManipulador.Pegar(id.Value);

            if (EsporteApp == null)
            {
                return HttpNotFound();
            }
            return View(EsporteApp);
        }

        // POST: EsporteApps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            var result = EsporteManipulador.Deletar(id);

            return RedirectToAction("Index");
        }
    }
}

SportsPromo.App.WebSiteAdm/Controllers/ReceptorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;

namespace SportsPromo.App.WebSiteAdm.Controllers
{
    public class ReceptorController : Controller
    {
        public ActionResult Index()
        {
            return View("OnePage");
        }
    }
}

SportsPromo.App.WebSiteAdm/Views/Receptor/Index.cshtml
@using SportsPromo.Comum.Html;
@model SportsPromo.Comum.Dados.PaginadoOrdenado<SportsPromo.App.Core.Modelos.EsporteApp>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Esporte")
</p>

<table class="table">
    <tr>
        <th>
            @Html.LinkDeOrdenacao(Model, e => e.Id)
        </th>
        <th>
            @Html.LinkDeOrdenacao(Model, e => e.Nome)
        </th>
        @*<th>

                <a href="@Url.Action("Index", new { page = Model.PaginaAtual , sort="Id", direction = Model.OrdemNome=="Id"? (Model.OrdemDirecao==0?1:0):0})">
                    @Html.DisplayNameFor(model => model.Model.Id)
                    @if (Model.OrdemNome == "Id")
                    {
                        <sub>
                            @if (Model.OrdemDirecao == 0)
                            {
                                @Html.Raw("ASC")
                            }
                            else
                            {
                                @Html.Raw("DESC")
                            }
                        </sub>
                    }
                </a>
            </th>*@
        @*<th>
                <a href="@Url.Action("Index", new { page = Model.PaginaAtual , sort="Nome", direction = Model.OrdemNome=="Nome"? (Model.OrdemDirecao==0?1:0):0})">
                    @Html.DisplayNameFor(model => model.Model.Nome)
                    @if (Model.OrdemNome == "Nome")
                    {
                        <sub>
                            @if (Model.OrdemDirecao == 0)
                            {
                                @Html.Raw("ASC")
                            }
                            else
                            {
                                @Html.Raw("DESC")
                            }
                        </sub>
                    }
                </a>
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model.Itens)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<nav aria-label="Page navigation">
    <ul class="pagination">
        <li>
            <a href="@Url.Action("Index", new { page = Model.PaginaAtual-1, sort = Model.OrdemNome,direction = Model.OrdemDirecao})" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        @for (var numeroDePagina = 1; numeroDePagina <= Model.ContagemDePaginas; numeroDePagina++)
        {
            <li class="@(numeroDePagina==Model.PaginaAtual?"active":"")"><a href="@Url.Action("Index", new { page = numeroDePagina, sort = Model.OrdemNome,direction = Model.OrdemDirecao})">@numeroDePagina</a></li>
        }
        <li>
            <a href="@Url.Action("Index", new { page = Model.PaginaAtual + 1, sort = Model.OrdemNome,direction = Model.OrdemDirecao})" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>

SportsPromo.App.WebSiteAdm/Views/Receptor/OnePage.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", "Receptor")
</p>
@*<script>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

    </script>*@

<table class="table" id="tabela-receptor">
    <thead>
        <tr>
            <th data-key="Id" data-sort="true">
                Id
            </th>
            <th data-key="Codigo" data-sort="true">
                Codigo
            </th>
            <th>
                Personalizada
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<nav aria-label="Page navigation" id="tabela-receptor-paginador"></nav>

<!-- Modal -->
<div class="modal fade" id="modal-receptor" tabindex="-1" role="dialog" aria-labelledby="modal-receptor-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-receptor-label">Alteração de Código do Receptor</h4>
            </div>
            <div class="modal-body">
                <input type="hidden" id="receptorId" value="0" />
                <div class="form-group">
                    <label for="receptorCodigo">Codigo</label>
                    <input type="text" class="form-control" id="receptorCodigo" placeholder="Código do Receptor">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary" id="salvarReceptor">Salvar</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/Scripts/GridJs.js")

    <script>
        var esporteGrid;
        $(document).ready(function () {
            var gridOptions = {
                Url: "http://localhost:44331/api/receptorapi/index/",
                Colunas: [
                    {
                        NomeDoCampo: "Id",
                        AtributosHtml: "",
                        CallbackDeRenderizacao: function (itemLinha, atributoColuna) {
                            var texto = itemLinha[atributoColuna];
                            var celula = $("<td />").addClass("text-right").append(texto);
                            return celula;
                        }
                    },
                    "Codigo",
                    {
                        CallbackDeRenderizacao: function (itemLinha, atributoColuna) {

                            var texto = `${itemLinha.Id} - ${itemLinha.Codigo}`;

                            var linkEdicao = $("<a/>")
                                .attr("href", "javascript:;")
                                .addClass("btn btn-primary")
                                .append("Editar")
                                .on("click", function () {
                                    ExibeFormularioEdicao(itemLinha.Id);
                                });
                            var celula = $("<td />").addClass("text-right").append(linkEdicao);

                            return celula;
                        }
                    }
                ],
                ConteinerDoPaginador: "#tabela-receptor-paginador"
            };
            esporteGrid = SetupGrid("#tabela-receptor", gridOptions);
            $("#salvarReceptor").on("click", function () { SalvarReceptor() });

        });
        function ExibeFormularioEdicao(itemId) {
            $.ajax("http://localhost:44331/api/receptorapi/get/", {
                method: "GET",
                data: { id: itemId }
            }).done(function (response, textStatus, jqXHR) {
                var modalReceptor = $("#modal-receptor");
                $("#receptorId").val(response.Id);
                $("#receptorCodigo").val(response.Codigo);
                modalReceptor.modal('show');
            });
        };

        function SalvarReceptor() {

            var putUrl = "http://localhost:44331/api/receptorapi/put/?id=";

            var receptorItem = {
                Id: $("#receptorId").val(),
                Codigo: $("#receptorCodigo").val(),
            }

            $.ajax(putUrl + receptorItem.Id, {
                method: "PUT",
                data: receptorItem
            }).done(function (response, textStatus, jqXHR) {
                receptorGrid.Recarregar();
                var modalReceptor = $("#modal-receptor");
                modalReceptor.modal('hide');
            });
        }


    </script>

}